# Generated by Django 4.2.7 on 2023-11-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_interface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpeningHours',
            new_name='RecurringHours',
        ),
        migrations.RenameModel(
            old_name='OpeningHoursSpecific',
            new_name='SpecificHours',
        ),
    ]
