# Generated by Django 4.2.7 on 2023-11-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_interface', '0002_rename_openinghours_recurringhours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
